### PR TITLE
Added optional percentage rounding

### PR DESCRIPTION
**Pull request by TurnrDev**

### CODE REVIEW

**Comment by TurnrDev** [comment]
If that works fine for you, with no errors, could you merge to master? :)

**Comment by flashmeow** [comment]
Done.
How did you find this project?

**Comment by TurnrDev** [comment]
I was going to create a function for it, but I was going to use it in several projects, so I decided I'd make a library for it. In my research for that, I found this. Any plans to release on PyPi?

Edit: I just noticed how new your repo is.

**Comment by flashmeow** [comment]
Yeah I was making it for one of my projects because no one else had.
I'm working on preparing it for PyPI. Check out that branch if you have any improvements.

**Comment by TurnrDev** [comment]
Ooh, you've made quite a few improvements. I'll take a proper look later :)

**Pull request merged**
