### PR TITLE
Add unit tests

### PR DESCRIPTION
**Pull request by joereynolds**

### CODE REVIEW

**Review by flashmeow — CHANGES_REQUESTED** [review]
Can we get rid of the pronouns?

**Comment by flashmeow** [comment]
On second thought, why don't we just add 
```
if __name__ == "__main__":
    import doctest
    doctest.testmod()
```
to the main file?

**Comment by joereynolds** [comment]
Sure thing, I should be able to get to this either tonight or tomorrow

**Comment by flashmeow** [comment]
If you want, I can do this right now.

**Comment by joereynolds** [comment]
It's entirely up to you, I'm not going to be able to get to it for at least a day

**Comment by flashmeow** [comment]
I've implemented the changes into master

**Pull request closed without merging**
